version: 2.1
workflows:
  version: 2
  branch:
    jobs:
      - makepress-orb/release-please-single:
          context: [lulubot]
          filters:
            branches:
              only:
                - main
      - makepress-orb/publish-docker:
          name: base
          context: [lulubot]
          requires:
            - makepress-orb/release-please-single
          filters:
            branches:
              only:
                - main
          username: LULUBOT_USERNAME
          password: GITHUB_TOKEN_LULUBOT
          image: dev-container
          registry: ghcr.io
          tag: latest
          dockerfile: base
      - makepress-orb/publish-docker:
          context: [lulubot]
          requires:
            - base
          filters:
            branches:
              only:
                - main
          username: LULUBOT_USERNAME
          password: GITHUB_TOKEN_LULUBOT
          image: dev-container
          registry: ghcr.io
          tag: python
          dockerfile: python
      - makepress-orb/publish-docker:
          context: [lulubot]
          requires:
            - base
          filters:
            branches:
              only:
                - main
          username: LULUBOT_USERNAME
          password: GITHUB_TOKEN_LULUBOT
          image: dev-container
          registry: ghcr.io
          tag: rust
          dockerfile: rust
  release:
    jobs:
      - makepress-orb/publish-docker:
          name: base
          context: [lulubot]
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          username: LULUBOT_USERNAME
          password: GITHUB_TOKEN_LULUBOT
          image: dev-container
          registry: ghcr.io
          tag: "${CIRCLE_TAG/v/''}"
          dockerfile: base
      - makepress-orb/publish-docker:
          context: [lulubot]
          requires:
            - base
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          username: LULUBOT_USERNAME
          password: GITHUB_TOKEN_LULUBOT
          image: dev-container
          registry: ghcr.io
          tag: "${CIRCLE_TAG/v/''}-python"
          dockerfile: python
      - makepress-orb/publish-docker:
          context: [lulubot]
          requires:
            - base
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          username: LULUBOT_USERNAME
          password: GITHUB_TOKEN_LULUBOT
          image: dev-container
          registry: ghcr.io
          tag: "${CIRCLE_TAG/v/''}-rust"
          dockerfile: rust
                
          
orbs:
  makepress-orb: makepress/makepress-orb@2.4.1